name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - archspec=0.2.3
  - asttokens=2.0.5
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - conda=24.3.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.12.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.7
  - debugpy=1.6.7
  - decorator=5.1.1
  - distro=1.8.0
  - executing=0.8.3
  - fmt=9.1.0
  - icu=73.1
  - idna=3.4
  - ipykernel=6.28.0
  - ipython=8.20.0
  - jedi=0.18.1
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libcurl=8.4.0
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=1.5.3
  - libmambapy=1.5.3
  - libnghttp2=1.57.0
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - menuinst=2.0.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.13
  - packaging=23.1
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - pyzmq=25.1.2
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.21
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - truststore=0.8.0
  - tzdata=2023c
  - urllib3=1.26.18
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
