name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - archspec=0.2.3
  - arrow-cpp=16.1.0
  - asttokens=2.0.5
  - attrs=24.2.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - boltons=23.0.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - conda=24.9.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.12.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.7
  - datasets=2.19.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - dill=0.3.8
  - distro=1.8.0
  - executing=0.8.3
  - filelock=3.13.1
  - fmt=9.1.0
  - frozendict=2.4.2
  - frozenlist=1.5.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - glog=0.5.0
  - huggingface_hub=0.24.6
  - icu=73.1
  - idna=3.4
  - ipykernel=6.28.0
  - ipython=8.20.0
  - jedi=0.18.1
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libabseil=20240116.2
  - libarchive=3.6.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.4.0
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libmamba=1.5.3
  - libmambapy=1.5.3
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libuuid=1.41.5
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - menuinst=2.0.1
  - multidict=6.1.0
  - multiprocess=0.70.15
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.15
  - orc=2.0.1
  - packaging=23.1
  - pandas=2.2.2
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.9.11
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.21
  - s2n=1.3.27
  - safetensors=0.4.5
  - setuptools=68.2.2
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tokenizers=0.20.1
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - transformers=4.45.2
  - truststore=0.8.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2023c
  - urllib3=1.26.18
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xxhash=0.8.0
  - xz=5.4.5
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.11.0
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - blinker==1.9.0
      - click==8.1.7
      - flask==3.1.0
      - flask-cors==5.0.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - markupsafe==3.0.2
      - oauthlib==3.2.2
      - python-dotenv==1.0.1
      - pytube==15.0.0
      - pyvirtualdisplay==3.0
      - requests-oauthlib==2.0.0
      - werkzeug==3.1.3
      - yt-dlp==2025.1.26
