---
title: "Rmd no more (atleast not while it is hindering me)"
date: "2023-04-11"
categories: [meta]
---

I had the initial goal here of having a space to help me have a space to write some words. In writing those words I was going to gain some skills in writing words in an order that works well to convey information.

However as one might expect I got bogged down in my efforts to get the website working. Specifically trying to get it to automatically build the rmd files to md with graphs included! This roadblock discouraged me from carrying on from using the website.

Regardless of all of my effort (6 months ago) it didnt work. It may work in the future and that would be great as then my blog can easily have some basic stats work in it if I want it to. What I am left with though is a website that can function quite alright at being a simple hosted blog.

All of the stuff that builds this website can be found [here](https://github.com/1jamesthompson1/1jamesthompson1.github.io).

Otherwise I expect to when post things worth my time when I have said time to post.