---
title: "Someone's being ripped off"
date: 2026-08-30
categories: ['observations']
---

I went to the internet ordered $200 worth of groceries paid $9 extra and it arrived at my front door 45 minutes later. With the immediacy of this and effort that requires $9 delivery just doesn't seem nearly enough to cover the cost of it all—someone is being ripped off ^[Not only that my delivery driver arrived in a $25k plus hybrid SUV]. I reckon the delivery driver is barely making it by, the people who supply the supermarket are screwed, the underpaid worker trooping around the store can't afford rent and well me, I just—probably—well overpaid for the food. 

Still feels like the future though ^[I remember seeing a old dragons den pitch for a weird refrigerated letter box to receive food delivers when you are out and it stays safe and cold. The dragons were like what a stupid idea within a year or two you will have food delivery accurate to within 15 minutes or something. They were wrong took 20+ years for me, still is the future!].