---
title: "Aiming to ride another day"
date: '2002-07-15'
categories: ["snowboarding"]
---

### Backstory 
Firstly a bit of background. I spent the 2023 snow season in Wānaka (Read more about it [here](https://www.sjtravels.co.nz/p/campervan-life-in-wanaka/))so that I could train at [Treble Cone](https://www.treblecone.com/) and [Cardrona](https://www.cardrona.com/) as I am competing on the [Freeride World Tour Qualifier series](https://www.freerideworldtour.com/qualifier/). This training entails alot of jumping off cliffs and attempting to land back on my snowboard (feet first!). Most of the time this does actually go quite well and I end up on my feet and ride away. However on the fateful day of the 22nd of August I was practicing doing a backflip off what the locals call "the diving board" at Treble cone.

{{< video https://youtu.be/p9-z9zbuHOY title="Crash that tore my ACL" >}}

Now I was trying to land and ride away but instead I tore my anterior cruciate ligament (ACL). This meant two things. ACL reconstruction surgery in November as well as no snowboarding for ~9 months.

### Back to today

This brings us to the here and now. I am back in Wānaka slowly starting to get back onto my snowboard. I am 5 days in and have noticed a newer idea floating around my head.

I feel that I have heard the phrase "Atleast there is tomorrow" said alot. A statement which in my eyes catches two sentiments;

- life carries on and,
- if you must you can probably try again

As I get back on my snowboard I need to test my knee, regain confidence in its ability. I want to slowly push it, slowly fold open the envelope. It really does make me feel silly, like a real fool just "riding around". Normally this feeling of lack of effort will become quite powerful. Yet these recent days I have noticed something peculiar. That when I call it a day (without doing anything spectacular) I almost feel happy and content that atleast I can still ride again tomorrow.

This comes from learning over the past year that some snowboarding is better than no snowboarding. I am not snowboarding just to enjoy the feeling of a turn or sweet carve, I am snowboarding to push myself and see what cool things I can do. Yet the turns and sweet carves are still magical and special in their own right. If I push myself too much, take too great of a risk I may miss out the basic magic of snowboarding as well as getting to truly see what cool things I can do on a board.

All of this is a long winded way of saying that I must make a decision on how much risk I want to take while snowboarding. I can push myself as far as I can go and have a higher risk of serious injury or play things safe, slowly push the envelope while keeping my body safe. To decide how much risk I am willing to take is hard. Yet maybe now after my first big injury I am happy to be a little bit on a safer side.

That said I am waiting on the green light from my physio and some fresh snow so I can reclaim that cliff!